name: Push website

on:
  push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      working-directory: web
      run: |
        sudo apt-get install bundler
        bundle install --deployment
    - name: Build website
      working-directory: web
      run: bundle exec jekyll build
    #- name: Push website
    #  run: rsync -av web/_site/ customer@botaniaweb.playat.ch:/var/www/botaniamod_net
